### ISSUE TITLE
A note...

### ISSUE THREAD

**Issue by Danappelxx** [stepanhruda/PostgreSQL-Swift#3]
Hi! We at [Zewo](https://github.com/Zewo) have been working on a web-framework for quite some time and came upon Elephant earlier today, and think it's great. If you're willing, we would love to talk about the possibility of collaboration over at the [Zewo Slack](https://zewo-slackin.herokuapp.com)!

**Comment by stepanhruda** [comment]
What kind of collaboration do you have in mind?
